name: Build and Release .deb Package

on:
  push:
    branches: [ main ]  # Trigger workflow on main branch push

permissions:
  contents: write

jobs:
  build-deb:
    name: Build Debian Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y dpkg-dev debhelper fakeroot

      - name: Build .deb package
        run: |
          mkdir -p build/pkg
          dpkg-deb --build pkg build/pkg/picoctf.deb

      - name: Upload Debian package artifact
        uses: actions/upload-artifact@v4
        with:
          name: picoctf-deb
          path: build/pkg/picoctf.deb

  create-tag:
    name: Create Git Tag
    needs: build-deb
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Latest Tag
        id: get_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          latest_version=$(echo $latest_tag | cut -d'.' -f2)
          new_version=$((latest_version + 1))
          new_tag="v1.$new_version.0"
          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV

      - name: Create and Push Tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG

  release:
    name: Create GitHub Release
    needs: create-tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Debian package artifact
        uses: actions/download-artifact@v4
        with:
          name: picoctf-deb
          path: build/pkg

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: "Release ${{ env.NEW_TAG }}"
          body: "🚀 New Debian package release: **${{ env.NEW_TAG }}**"
          draft: false
          prerelease: false
          files: build/pkg/picoctf.deb
