name: Build and Release .deb Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-deb:
    name: Build Debian Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y dpkg-dev debhelper fakeroot

      - name: Prepare Package Structure
        run: |
          mkdir -p pkg/DEBIAN
          mkdir -p pkg/usr/bin
          mkdir -p pkg/usr/share/man/man1

          # Create DEBIAN/control file
          cat <<EOF > pkg/DEBIAN/control
          Package: picoctf
          Version: 1.0.0
          Architecture: all
          Maintainer: Your Name <your.email@example.com>
          Description: A sample picoCTF package with multiple scripts
          Depends: libc6 (>= 2.27)
          Section: misc
          Priority: optional
          EOF

          # Copy scripts to /usr/bin/ (KEEP .sh extensions)
          cp scripts/*.sh pkg/usr/bin/
          chmod +x pkg/usr/bin/*.sh  # Make them executable

          # Copy man pages
          cp docs/MANUAL/*.1 pkg/usr/share/man/man1/

          # Compress man pages
          gzip -f pkg/usr/share/man/man1/*.1

      - name: Build .deb package
        run: |
          dpkg-deb --build pkg build/pkg/picoctf.deb

      - name: Upload Debian package artifact
        uses: actions/upload-artifact@v4
        with:
          name: picoctf-deb
          path: build/pkg/picoctf.deb

  release:
    name: Create GitHub Release
    needs: build-deb
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Debian package artifact
        uses: actions/download-artifact@v4
        with:
          name: picoctf-deb
          path: build/pkg

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          name: "Release v1.0.0"
          body: "🚀 New Debian package release: **v1.0.0**"
          draft: false
          prerelease: false
          files: build/pkg/picoctf.deb
